services:
  - type: web
    name: bookstore-frontend
    buildCommand: npm install --production=false && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    env:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://bookstoreapp-2-y94s.onrender.com